#bin location model
define binloc model
(
  size [25 10 2.0]

  block(
	color "sienna"
	points 4
	point[0] [0 0.9]
	point[1] [1 0.9]
	point[2] [1 1]
	point[3] [0 1]
	z [0 2]
  )

  block(
	color "sienna"
	points 4
	point[0] [0.97 0]
	point[1] [1 0]
	point[2] [1 0.9]
	point[3] [0.97 0.9]
	z [0 2]
  )

  block(
	color "sienna"
	points 4
	point[0] [0 0]
	point[1] [0.03 0]
	point[2] [0.03 0.9]
	point[3] [0 0.9]
	z [0 2]
  )
)
