define shrub model
(
  size [1 1 1]
  color "green"
  gui_move 0

  block(
	points 4
	point[0] [0.2 0.2]
	point[1] [0.8 0.2]
	point[2] [0.8 0.8]
	point[3] [0.2 0.8]
	z [0 0.05]
  )

  block(
	points 4
	point[0] [0.2 0.2]
	point[1] [0.8 0.2]
	point[2] [0.8 0.8]
	point[3] [0.2 0.8]
	z [0.05 0.10]
  )

  block(
	points 4
	point[0] [0.1 0.1]
	point[1] [0.9 0.1]
	point[2] [0.9 0.9]
	point[3] [0.1 0.9]
	z [0.10 0.15]
  )

  block(
	points 4
	point[0] [0.1 0.1]
	point[1] [0.9 0.1]
	point[2] [0.9 0.9]
	point[3] [0.1 0.9]
	z [0.15 0.20]
  )

  block(
	points 4
	point[0] [0 0]
	point[1] [1 0]
	point[2] [1 1]
	point[3] [0 1]
	z [0.20 0.25]
  )

  block(
	points 4
	point[0] [0 0]
	point[1] [1 0]
	point[2] [1 1]
	point[3] [0 1]
	z [0.25 0.30]
  )

  block(
	points 4
	point[0] [0.05 0.05]
	point[1] [0.95 0.05]
	point[2] [0.95 0.95]
	point[3] [0.05 0.95]
	z [ 0.3 0.35]
  )

  block(
	points 4
	point[0] [0.1 0.1]
	point[1] [0.9 0.1]
	point[2] [0.9 0.9]
	point[3] [0.1 0.9]
	z [0.35 0.4]
  )

  block(
	points 4
	point[0] [0.15 0.15]
	point[1] [0.85 0.15]
	point[2] [0.85 0.85]
	point[3] [0.15 0.85]
	z [0.4 0.45]
  )

  block(
	points 4
	point[0] [0.2 0.2]
	point[1] [0.8 0.2]
	point[2] [0.8 0.8]
	point[3] [0.2 0.8]
	z [0.45 0.5]
  )

  block(
	points 4
	point[0] [0.25 0.25]
	point[1] [0.75 0.25]
	point[2] [0.75 0.75]
	point[3] [0.25 0.75]
	z [0.5 0.55]
  )

  block(
	points 4
	point[0] [0.3 0.3]
	point[1] [0.7 0.3]
	point[2] [0.7 0.7]
	point[3] [0.3 0.7]
	z [0.55 0.6]
  )

  block(
	points 4
	point[0] [0.35 0.35]
	point[1] [0.65 0.35]
	point[2] [0.65 0.65]
	point[3] [0.35 0.65]
	z [0.6 0.65]
  )

  block(
	points 4
	point[0] [0.4 0.4]
	point[1] [0.6 0.4]
	point[2] [0.6 0.6]
	point[3] [0.4 0.6]
	z [0.65 0.7]
  )
  
  block(
	points 4
	point[0] [0.45 0.45]
	point[1] [0.55 0.45]
	point[2] [0.55 0.55]
	point[3] [0.45 0.55]
	z [0.7 0.75]
  )
)
